project:
  type: website
  output-dir: docs
  post-render: "scripts/decktape.sh"   
  render:
    - "*.qmd"
    - "!assignments/files/"
    - "!files/tutorials/"   

website:
  title: "EC313 - Taxation"
  navbar:
    pinned: true
    background: "#9e32a8"
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Assignments"
        file: assignments/index.qmd

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
      
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Course content"
          contents:
            - text: "Intro to Public Finance"
              file: content/introtopf.qmd
            - text: "Tax Incidence"
              file: content/incidence.qmd
            - text: "Taxation and Efficiency"
              file: content/efficiency.qmd
            - text: "Introduction to Stata"
              file: content/introtostata.qmd
            - text: "Efficient and Equitable Taxation"
              file: content/equitable.qmd
            - text: "The Personal Income Tax"
              file: content/personaltax.qmd
            - text: "Personal Taxation and Behaviour"
              file: content/taxbehaviour.qmd

              
    - title: "Assignments"
      style: "docked"
      search: false
      background: dark
      contents:
      
        - section: "Overview"
          contents:
            - assignments/index.qmd
        - section: "Assignments"
          contents:
            - text: "Assignment 1"
              file: assignments/assign1.qmd
              
format:
  html:
    code-overflow: wrap
    theme: 
      - litera
      - html/custom.scss
    toc: true


